export namespace constants {

  export namespace headers.response {

    // standard server header
    export const SERVER = 'SERVER';

    // standard forwarded for header
    export const X_Forwarded_For = 'X-Forwarded-For';

    // standard forwarded proto header
    export const X_Forwarded_Proto = 'X-Forwarded-Proto';

    // standard forwarded port header
    export const X_Forwarded_Port = 'X-Forwarded-Port';

    // indicate the response is generated by which applet or which product
    export const NODESWORK_HEADER_PRODUCER = 'X-NODESWORK-PRODUCER';

    // indicate the response is generated by which particular host
    export const NODESWORK_HEADER_PRODUCER_HOST = 'X-NODESWORK-PRODUCER-HOST';
  }
}
